name = "ParallelAnalysis"
uuid = "c8fef40c-3641-40f1-b0ae-e08425a5d2fc"
authors = ["Takumi Shibuya <sep10.taku.izum@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
